version: '3.3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - database
      - apiserver
    ports:
      - "9999:9999"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - apiserver
    volumes:
      - .:/app/frontend
      - /app/frontend/node_modules


  mysql:
    image: 'mysql:5.7.22'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: todos_user
      MYSQL_PASSWORD: todos_pass
      MYSQL_DATABASE: todos_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - database
    volumes:
      - "./conf/mysql:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql


volumes:
  db-data:

networks:
  database:
  apiserver:

