version: '3.3'

services:
  #TODO add application services
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - database
    ports:
      - "9999:9999"

  #frontend PORT 8888


  mysql:
    image: 'mysql:5.7.22'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: todos_user
      MYSQL_PASSWORD: todos_pass
      MYSQL_DATABASE: todos_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - database
    volumes:
      - "./conf/mysql:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql


volumes:
  db-data:

networks:
  database:

