CREATE TABLE `todos` (
  id int(11) NOT NULL AUTO_INCREMENT,
  text VARCHAR(256) DEFAULT NULL,
  done TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
